
---
- name: web-server configuration
  hosts: slaveA
  become: yes

  roles:
    - common
    - webserver
    - security

- name: db configuration
  hosts: slaveB
  become: yes

  roles:
    - common
    - security
